name: 'MKMBA setup-go (test)'
description: 'Sets up Go with MKMBA defaults and Dockerfile version extraction'

inputs:
  go-version:
    description: 'Override default or dockerfile extract Go version. (Last resort!)'
    required: false
  dockerfile:
    description: 'Use a go version matching the golang image in the specified Dockerfile'
    required: false

runs:
  using: composite
  steps:
    - name: Extract Go version from Dockerfile
      if: inputs.dockerfile != ''
      id: extract-version
      shell: bash
      # NOTE: uses only the first version found in the Dockerfile... maybe warn if multiple?
      run: |
        GO_VERSION=$(grep -E '^FROM golang:' ${{ inputs.dockerfile }} | sed -E 's/^FROM golang:([0-9]+\.[0-9]+)(-.*)?.*$/\1/' | head -n 1)
        echo "extracted_version=${GO_VERSION}" >> "$GITHUB_OUTPUT"

    - name: find go.sum
      id: go-sum
      shell: bash
      run: |
        files=$(find "${{ github.workspace }}" -name go.sum)
        echo "paths<<EOF" >> $GITHUB_OUTPUT
        echo "$files" >> $GITHUB_OUTPUT
        echo "EOF" >> $GITHUB_OUTPUT

    - name: Setup Go
      uses: actions/setup-go@v5
      with:
        # If neither go-version nor dockerfile is provided, use a default production go version.
        go-version: ${{ inputs.go-version || steps.extract-version.outputs.extracted_version || '1.25' }}
        check-latest: true
        cache: true
        cache-dependency-path: ${{ steps.go-sum.outputs.paths }}

    - name: Set GOTOOLCHAIN
      shell: bash
      run: echo "GOTOOLCHAIN=local" >> $GITHUB_ENV
