name: check-terraform

on:
  pull_request:
    branches: [ "main" ]

jobs:
  compliance-tests:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    # Install the latest version of Terraform CLI
    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v1

    # Checks that all Terraform configuration files adhere to a canonical format
    - name: Terraform Format
      run: terraform fmt -check -recursive
